apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dwd-api
  title: Deutsches Wetter Dienst API
  description: "Diese API stellt Informationen zur BUND DWD API bereit."
  annotations:
    backstage.io/techdocs-ref: dir:./docs
    # Weitere optionale Annotationen, z. B. für GitHub-Repository, Version, etc.
spec:
  type: openapi
  lifecycle: production
  owner: team-awesome
  definition:
    type: openapi
    $text: https://raw.githubusercontent.com/adessowan/dwd/refs/heads/main/dwd.yaml
